name: Terraform Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      #- name: Set up SSH key
       # run: |
        #  echo "${{ secrets.PRIVATE_KEY }}" > moses.pem
         # chmod 600 moses.pem
         # ssh-keygen -y -f moses.pem > public_key.pem

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform
        run: terraform plan -out=tfplan

      - name: Apply Terraform
        run: terraform apply -auto-approve tfplan

      - name: Save Private Key to Artifact
        run: echo "${{ steps.<TERRAFORM_STEP_NAME>.outputs.private_key_pem }}" > private_key.pem
      - uses: actions/upload-artifact@v2
        with:
          name: private-key-artifact
          path: private_key.pem

      - name: output Terraform
        run: terraform output
